# plotting the PCA values generated by deeptools #

library(data.table)
library(tidyverse)
library(ggrepel)

# Load data
pca_long <- read.table("/Users/zofiapiszka/Desktop/cuttag/pca_coordinates_36.tab.tsv", header=TRUE, sep="\t")
pca <- pca_long[1:2, 1:9]
pca <- as.data.frame(t(pca))
colnames(pca) <- c("PC1", "PC2")
pca <- pca[2:9, ]

samples <- read.csv("/Users/zofiapiszka/Desktop/cuttag/deeptools_pca_sample_list.csv")
samples <- as.data.frame(samples)
pca$Cluster <- c(samples$Cluster[5:8], samples$Cluster[13:16])

# calculate the variance explained by PC1 and PC2
sum = sum(pca_long$Eigenvalue)
var_1 <- round(pca_long$Eigenvalue[1]/sum * 100, 2)
var_2 <- round(pca_long$Eigenvalue[2]/sum * 100, 2)

# Plot with labels next to points
p <- ggplot(pca, aes(PC1, PC2, color=Cluster)) +
  geom_point(size=5, alpha=0.8) +
  geom_text_repel(aes(label=rownames(pca)), size=5, max.overlaps=20) +  # Labels!
  labs(title="PCA of the H3K36me3 samples", 
       x=paste0("PC1 (", var_1, "%)"),
       y=paste0("PC2 (", var_2, "%)")) +
  theme_classic() +
  theme(plot.title = element_text(size = 24, hjust = 0.5,  margin = margin(t = 10)), # margin adds space above the plot title, pushing it down
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.title = element_text(size = 18),
        legend.text  = element_text(size = 16),
        legend.position="right")
print(p)


