#!/bin/bash
#$ -cwd
#$ -V
#$ -l tmem=12G
#$ -l h_vmem=12G
#$ -l h_rt=12:0:0
#$ -R y
#$ -j y
#$ -N kmetstat_counts
#$ -o /SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/kmetstat/reports/kmetstat_counts.out 

source /SAN/colcc/MMRd_HCEC_genomes/myCOLCCenv.sh 

projPath="/SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/raw_data/X204SC24121583-Z01-F001/01.RawData"
outDir="/SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/kmetstat/output"

sampleList="${projPath}fastq_list.csv"

#unzip the fastq files
while read -r sample; do
 gzip -d -k "${projPath}/${sample}_1.fq.gz"
 gzip -d -k "${projPath}/${sample}_2.fq.gz"
done < "$sampleList"

#run kmetloop.sh which counts barcodes sequences corresponding to kmet panel spike-in from sequencing data

while read -r sample; do

read1="${projPath}/${sample}_1.fq"
read2="${projPath}/${sample}_2.fq"
samplename=$(echo `basename "$read1" _1.fq`)


echo `basename "$read1"` > "$samplename"_R1.txt
for barcode in TTCGCGCGTAACGACGTACCGT CGCGATACGACCGCGTTACGCG CGACGTTAACGCGTTTCGTACG CGCGACTATCGCGCGTAACGCG CCGTACGTCGTGTCGAACGACG CGATACGCGTTGGTACGCGTAA TAGTTCGCGACACCGTTCGTCG TCGACGCGTAAACGGTACGTCG TTATCGCGTCGCGACGGACGTA CGATCGTACGATAGCGTACCGA CGCATATCGCGTCGTACGACCG ACGTTCGACCGCGGTCGTACGA ACGATTCGACGATCGTCGACGA CGATAGTCGCGTCGCACGATCG CGCCGATTACGTGTCGCGCGTA ATCGTACCGCGCGTATCGGTCG CGTTCGAACGTTCGTCGACGAT TCGCGATTACGATGTCGCGCGA ACGCGAATCGTCGACGCGTATA CGCGATATCACTCGACGCGATA CGCGAAATTCGTATACGCGTCG CGCGATCGGTATCGGTACGCGC GTGATATCGCGTTAACGTCGCG TATCGCGCGAAACGACCGTTCG CCGCGCGTAATGCGCGACGTTA CCGCGATACGACTCGTTCGTCG GTCGCGAACTATCGTCGATTCG CCGCGCGTATAGTCCGAGCGTA CGATACGCCGATCGATCGTCGG CCGCGCGATAAGACGCGTAACG CGATTCGACGGTCGCGACCGTA TTTCGACGCGTCGATTCGGCGA ;
do
  	grep -c "$barcode" "$read1" >> "$samplename"_R1.txt  
done

echo `basename "$read2"` >> "$samplename"_R2.txt
for barcode in TTCGCGCGTAACGACGTACCGT CGCGATACGACCGCGTTACGCG CGACGTTAACGCGTTTCGTACG CGCGACTATCGCGCGTAACGCG CCGTACGTCGTGTCGAACGACG CGATACGCGTTGGTACGCGTAA TAGTTCGCGACACCGTTCGTCG TCGACGCGTAAACGGTACGTCG TTATCGCGTCGCGACGGACGTA CGATCGTACGATAGCGTACCGA CGCATATCGCGTCGTACGACCG ACGTTCGACCGCGGTCGTACGA ACGATTCGACGATCGTCGACGA CGATAGTCGCGTCGCACGATCG CGCCGATTACGTGTCGCGCGTA ATCGTACCGCGCGTATCGGTCG CGTTCGAACGTTCGTCGACGAT TCGCGATTACGATGTCGCGCGA ACGCGAATCGTCGACGCGTATA CGCGATATCACTCGACGCGATA CGCGAAATTCGTATACGCGTCG CGCGATCGGTATCGGTACGCGC GTGATATCGCGTTAACGTCGCG TATCGCGCGAAACGACCGTTCG CCGCGCGTAATGCGCGACGTTA CCGCGATACGACTCGTTCGTCG GTCGCGAACTATCGTCGATTCG CCGCGCGTATAGTCCGAGCGTA CGATACGCCGATCGATCGTCGG CCGCGCGATAAGACGCGTAACG CGATTCGACGGTCGCGACCGTA TTTCGACGCGTCGATTCGGCGA ;
do
  	grep -c "$barcode" "$read2" >> "$samplename"_R2.txt
done 

#paste both reads into a single file
paste "$samplename"_R1.txt "$samplename"_R2.txt | column -s $'\t' -t > "$samplename"_bc_counts.txt

done < "$sampleList"

#move all output file to output folder
mv *_bc_counts.txt $outDir
