#!/bin/bash
#$ -cwd
#$ -V
#$ -l tmem=12G
#$ -l h_vmem=12G
#$ -l h_rt=12:0:0
#$ -R y
#$ -j y
#$ -N kmetstat_counts_array
#$ -t 1-16
#$ -o /SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/kmetstat/reports/kmetstat_counts_array.out 

source /SAN/colcc/MMRd_HCEC_genomes/myCOLCCenv.sh 

tid=${SGE_TASK_ID}

#set working directory containing all the fq files
DIR="/SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/raw_data/X204SC24121583-Z01-F001/01.RawData"
OUTDIR="/SAN/colcc/MMRd_HCEC_genomes/cuttag_batch2/kmetstat/output"

#list your input files
files=$(ls $DIR/*/*_1.fq) 
arr=($files)
sample=${arr[$tid]}

#creating sampleID, common for matched _1 and _2 files 
sampleID=$(echo `basename $sample _1.fq`)

#run kmetloop.sh which  counts barcodes sequences corresponding to kmet panel spike-in from sequencing data

read1=$DIR/*/*/"$sampleID"_1.fq
read2=$DIR/*/*/"$sampleID"_2.fq
samplename=$(echo `basename $read1 _1.fq`)


echo `basename $read1` > "$samplename"_R1.txt
for barcode in TTCGCGCGTAACGACGTACCGT CGCGATACGACCGCGTTACGCG CGACGTTAACGCGTTTCGTACG CGCGACTATCGCGCGTAACGCG CCGTACGTCGTGTCGAACGACG CGATACGCGTTGGTACGCGTAA TAGTTCGCGACACCGTTCGTCG TCGACGCGTAAACGGTACGTCG TTATCGCGTCGCGACGGACGTA CGATCGTACGATAGCGTACCGA CGCATATCGCGTCGTACGACCG ACGTTCGACCGCGGTCGTACGA ACGATTCGACGATCGTCGACGA CGATAGTCGCGTCGCACGATCG CGCCGATTACGTGTCGCGCGTA ATCGTACCGCGCGTATCGGTCG CGTTCGAACGTTCGTCGACGAT TCGCGATTACGATGTCGCGCGA ACGCGAATCGTCGACGCGTATA CGCGATATCACTCGACGCGATA CGCGAAATTCGTATACGCGTCG CGCGATCGGTATCGGTACGCGC GTGATATCGCGTTAACGTCGCG TATCGCGCGAAACGACCGTTCG CCGCGCGTAATGCGCGACGTTA CCGCGATACGACTCGTTCGTCG GTCGCGAACTATCGTCGATTCG CCGCGCGTATAGTCCGAGCGTA CGATACGCCGATCGATCGTCGG CCGCGCGATAAGACGCGTAACG CGATTCGACGGTCGCGACCGTA TTTCGACGCGTCGATTCGGCGA ;
do
  	grep -c $barcode $read1 >> "$samplename"_R1.txt  
done

echo `basename $read2` >> "$samplename"_R2.txt
for barcode in TTCGCGCGTAACGACGTACCGT CGCGATACGACCGCGTTACGCG CGACGTTAACGCGTTTCGTACG CGCGACTATCGCGCGTAACGCG CCGTACGTCGTGTCGAACGACG CGATACGCGTTGGTACGCGTAA TAGTTCGCGACACCGTTCGTCG TCGACGCGTAAACGGTACGTCG TTATCGCGTCGCGACGGACGTA CGATCGTACGATAGCGTACCGA CGCATATCGCGTCGTACGACCG ACGTTCGACCGCGGTCGTACGA ACGATTCGACGATCGTCGACGA CGATAGTCGCGTCGCACGATCG CGCCGATTACGTGTCGCGCGTA ATCGTACCGCGCGTATCGGTCG CGTTCGAACGTTCGTCGACGAT TCGCGATTACGATGTCGCGCGA ACGCGAATCGTCGACGCGTATA CGCGATATCACTCGACGCGATA CGCGAAATTCGTATACGCGTCG CGCGATCGGTATCGGTACGCGC GTGATATCGCGTTAACGTCGCG TATCGCGCGAAACGACCGTTCG CCGCGCGTAATGCGCGACGTTA CCGCGATACGACTCGTTCGTCG GTCGCGAACTATCGTCGATTCG CCGCGCGTATAGTCCGAGCGTA CGATACGCCGATCGATCGTCGG CCGCGCGATAAGACGCGTAACG CGATTCGACGGTCGCGACCGTA TTTCGACGCGTCGATTCGGCGA ;
do
  	grep -c $barcode $read2 >> "$samplename"_R2.txt
done 

#paste both reads into a single file
paste "$samplename"_R1.txt "$samplename"_R2.txt  | column -s '' -t > "$samplename"_bc_counts.txt

#move all output file to output folder
mv *_bc_counts.txt $OUTDIR